# ============================================================================
# SIMPLIFIED NAV2 PARAMETERS - OPTIMIZED FOR LOW CPU USAGE
# ============================================================================
# This configuration prioritizes computational efficiency over maximum performance
# Designed to minimize CPU spikes while maintaining functional navigation

amcl:
  ros__parameters:
    use_sim_time: False
    
    # Reduced particle count for lower CPU usage
    max_particles: 200                          # Reduced from 800
    min_particles: 100                          # Reduced from 300
    
    # Motion model - simplified
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    
    # Frame configuration
    base_frame_id: "base_footprint"
    global_frame_id: "map"
    odom_frame_id: "odom"
    
    # Laser processing - reduced load
    laser_max_range: 8.0                        # Reduced from 15.0
    max_beams: 30                               # Reduced from 80
    beam_skip_distance: 1.0                     # Increased from 0.5
    do_beamskip: true                           # Enable to reduce processing
    
    # Less frequent updates
    update_min_d: 0.25                          # Increased from 0.1
    update_min_a: 0.2                           # Increased from 0.05
    resample_interval: 3                        # Increased from 2
    
    # Simplified parameters
    pf_err: 0.2                                 # Increased tolerance
    pf_z: 0.9                                   # Reduced confidence requirement
    recovery_alpha_fast: 0.0                   # Disabled for stability
    recovery_alpha_slow: 0.0                   # Disabled for stability
    
    laser_model_type: "likelihood_field"
    robot_model_type: "nav2_amcl::DifferentialMotionModel"  # Simpler than Omni
    scan_topic: scan_restamped
    transform_tolerance: 1.0                    # More tolerant

bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: map
    robot_base_frame: base_footprint
    odom_topic: odom
    
    # Reduced frequency for lower CPU
    bt_loop_duration: 100                       # Reduced to 10Hz from 20Hz
    default_server_timeout: 20
    
    # Simple behavior tree
    default_nav_to_pose_bt_xml: "/opt/ros/humble/share/nav2_bt_navigator/behavior_trees/navigate_to_pose_simple.xml"
    default_nav_through_poses_bt_xml: "/opt/ros/humble/share/nav2_bt_navigator/behavior_trees/navigate_through_poses_simple.xml"
    
    # Basic plugins only
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_goal_updated_condition_bt_node
    - nav2_navigate_to_pose_action_bt_node

bt_navigator_navigate_through_poses_rclcpp_node:
  ros__parameters:
    use_sim_time: False

bt_navigator_navigate_to_pose_rclcpp_node:
  ros__parameters:
    use_sim_time: False

controller_server:
  ros__parameters:
    use_sim_time: False
    
    # Reduced frequency
    controller_frequency: 8.0                   # Reduced from 15.0
    
    # Simple controller - DWB instead of MPPI
    controller_plugins: ["FollowPath"]
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["general_goal_checker"]
    
    # Tolerances
    failure_tolerance: 0.5
    
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.2
      movement_time_allowance: 10.0
      
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.5                    # More tolerant
      yaw_goal_tolerance: 0.5
      
    # Simple DWB controller instead of MPPI
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      
      # Basic velocity limits
      max_vel_x: 0.3
      min_vel_x: -0.2
      max_vel_y: 0.0                            # Differential drive
      min_vel_y: 0.0
      max_vel_theta: 1.0
      min_vel_theta: -1.0
      
      # Simple acceleration limits
      acc_lim_x: 0.5
      acc_lim_y: 0.0
      acc_lim_theta: 1.0
      
      # Reduced trajectory sampling
      vx_samples: 8                             # Reduced from default
      vy_samples: 1                             # Differential drive
      vtheta_samples: 8                         # Reduced from default
      sim_time: 1.0                             # Reduced prediction time
      
      # Simple critics
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      
      # Basic critic weights
      BaseObstacle.scale: 0.02
      PathAlign.scale: 32.0
      PathDist.scale: 24.0
      GoalAlign.scale: 24.0
      GoalDist.scale: 24.0

local_costmap:
  local_costmap:
    ros__parameters:
      # Reduced update frequencies
      update_frequency: 5.0                     # Reduced from 19.0
      publish_frequency: 2.0                    # Reduced from 19.0
      
      global_frame: odom
      robot_base_frame: base_footprint
      use_sim_time: False
      rolling_window: True
      
      # Smaller costmap for efficiency
      width: 6                                  # Reduced from 12
      height: 6                                 # Reduced from 12
      resolution: 0.1                           # Coarser from 0.05
      
      # Simple footprint
      footprint: "[ [0.3, 0.15], [0.3, -0.15], [-0.4, -0.15], [-0.4, 0.15] ]"
      
      # Basic plugins only
      plugins: ["obstacle_layer", "inflation_layer"]
      
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan_restamped
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 6.0               # Reduced range
          obstacle_max_range: 4.0               # Reduced range
          raytrace_min_range: 0.1
          obstacle_min_range: 0.1
          
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.3                   # Smaller radius

global_costmap:
  global_costmap:
    ros__parameters:
      # Very low update frequencies
      update_frequency: 2.0                     # Reduced from 10.0
      publish_frequency: 1.0                    # Reduced from 5.0
      
      global_frame: map
      robot_base_frame: base_footprint
      use_sim_time: False
      
      # Coarser resolution
      resolution: 0.1                           # Coarser from 0.05
      track_unknown_space: True
      static_map: True
      
      # Same footprint
      footprint: "[ [0.3, 0.15], [0.3, -0.15], [-0.4, -0.15], [-0.4, 0.15] ]"
      
      # Minimal plugins
      plugins: ["static_layer", "inflation_layer"]
      
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.3

map_saver:
  ros__parameters:
    use_sim_time: False
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

planner_server:
  ros__parameters:
    use_sim_time: False
    expected_planner_frequency: 2.0             # Much reduced from 12.0
    planner_plugins: ["GridBased"]
    
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"  # Simpler than SmacPlanner2D
      tolerance: 0.2
      use_astar: false                          # Dijkstra is simpler
      allow_unknown: true

smoother_server:
  ros__parameters:
    smoother_plugins: ["simple_smoother"]
    
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-8
      max_its: 500                              # Reduced iterations
      do_refinement: False                      # Disabled for speed

behavior_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 5.0                        # Reduced from 10.0
    behavior_plugins: ["spin", "backup", "wait"]
    
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    wait:
      plugin: "nav2_behaviors/Wait"
      
    global_frame: map
    robot_base_frame: base_footprint
    use_sim_time: False
    
    # Conservative motion limits
    max_rotational_vel: 0.5
    min_rotational_vel: 0.1
    rotational_acc_lim: 0.5

robot_state_publisher:
  ros__parameters:
    use_sim_time: False

waypoint_follower:
  ros__parameters:
    use_sim_time: False
    loop_rate: 5                                # Reduced from 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 1000

velocity_smoother:
  ros__parameters:
    smoothing_frequency: 10.0                   # Reduced from 20.0
    scale_velocities: False
    feedback: "OPEN_LOOP"
    
    # Conservative limits
    max_velocity: [0.3, 0.0, 1.0]
    min_velocity: [-0.2, 0.0, -1.0]
    max_accel: [0.3, 0.0, 1.0]
    max_decel: [-0.5, 0.0, -2.0]
    
    odom_topic: "odom"
    odom_duration: 0.2
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 2.0
